config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users 

  

devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
end
  resources :sectors

  root 'sectors#index'

end

app/models/sector.rb
class Sector < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token, :only => [:index, :show, :destroy, :create, :update]
  respond_to :html, :json
  # GET /sectors
  # GET /sectors.json
  def index
    @sector = Sector.all
     respond_with(@sectors) do |format|
      format.json { render :json => @sector.as_json }
      format.html
    end
  end

  # GET /sectors/1
  # GET /sectors/1.json
  def show
    respond_with(@sector.as_json)
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors
  # POST /sectors.json
  def create
    @sector = Sector.new(sector_params)
    if @sector.save
      render json: @sector.as_json, status: :ok
    else
      render json: {sector: @sector.errors, status: :no_content}
    end
  end

  # PATCH/PUT /sectors/1
  # PATCH/PUT /sectors/1.json
  def update
     if @sector.update_attributes(sector_params)
      render json: @sector.as_json, status: :ok 
    else
      render json: {sector: @sector.errors, status: :unprocessable_entity}
    end
  end

  # DELETE /sectors/1
  # DELETE /sectors/1.json
  def destroy
    @sector.destroy
    respond_to do |format|
      format.html { redirect_to sectors_url, notice: 'Sector was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sector_params
      params.require(:sector).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="myapplication">
<head >
	
    
  <title>To Do List Intranet Iosento</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<div class="container">

<ul class="nav nav-pills centered">
  <li class="active"><%= link_to "Inicio", root_path %></li>
  <% if user_signed_in? %>
  <li><a href="#/sectors/new">Crear una Nueva Lista</a></li>
  <li><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></li>
  <%else%>
<li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
 <% end %>


</ul>

</div>

<p class="notice"><%= notice %></p>	<p class="alert"><%= alert %></p>
	

<div class="container"  ng-view>
	<%= yield %>
</div>

</body>
</html>

app/views/sectors/_form.html.erb
<ul class="nav nav-pills centered">
  <li class="active"><a href="#">Inicio</a></li>
  <li><a href="#/sectors/new">Crear una Nueva Lista</a></li>
  <li><a href="#">Cerrar Sesión</a></li>
  <li><%= link_to "Iniciar Sesión", new_user_session_path %></li>
</ul>

app/views/sectors/edit.html.erb
<h1>Editing Sector</h1>

<%= render 'form' %>

<%= link_to 'Show', @sector %> |
<%= link_to 'Back', sectors_path %>

app/views/sectors/new.html.erb
<h1>New Sector</h1>

<%= render 'form' %>

<%= link_to 'Back', sectors_path %>

app/views/sectors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sector.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sector.status %>
</p>

<%= link_to 'Edit', edit_sector_path(@sector) %> |
<%= link_to 'Back', sectors_path %>